-- 데이터스페이스 생성
CREATE TABLESPACE TREELINK
DATAFILE 'treelink_data01.dbf'
SIZE 100M -- 100mb쓸거에요
AUTOEXTEND ON NEXT 10M -- 부족하면 조금씩 땅겨올거에요
MAXSIZE UNLIMITED; -- 무한정 땅겨올거에요

-- 계정 생성 / 권한 부여
CREATE USER TREELINK IDENTIFIED BY TREELINK
DEFAULT TABLESPACE TREELINK
QUOTA UNLIMITED ON TREELINK;
GRANT CONNECT, RESOURCE TO TREELINK;

-- 계정 날리기
DROP USER TREELINK CASCADE;
-- 데이터스페이스 날리기
DROP TABLESPACE TREELINK INCLUDING CONTENTS AND DATAFILES;