CREATE TABLE MEMBER(
  MEMBER_NO NUMBER PRIMARY KEY,
  ID VARCHAR2(300) NOT NULL,
  PWD VARCHAR2(300) NOT NULL,
  NAME VARCHAR2(300) NOT NULL,
  NICKNAME VARCHAR2(300) NOT NULL
);
COMMENT ON TABLE MEMBER IS '회원';
COMMENT ON COLUMN MEMBER.MEMBER_NO IS '아이디';
COMMENT ON COLUMN MEMBER.PWD IS '비밀번호';
COMMENT ON COLUMN MEMBER.NAME IS '이름';

CREATE TABLE ROLE_INFO(
  ROLE_NO NUMBER PRIMARY KEY,
  NAME VARCHAR2(30) NOT NULL
);
COMMENT ON TABLE ROLE_INFO IS '권한';
COMMENT ON COLUMN ROLE_INFO.ROLE_NO IS '권한 식별번호';
COMMENT ON COLUMN ROLE_INFO.NAME IS '권한 이름';

CREATE TABLE MEMBER_ROLE(
  MEMBER_NO NUMBER REFERENCES MEMBER(MEMBER_NO),
  ROLE_NO NUMBER REFERENCES ROLE_INFO(ROLE_NO)
);
COMMENT ON TABLE MEMBER_ROLE IS '회원-권한';
COMMENT ON COLUMN MEMBER_ROLE.MEMBER_NO IS '회원번호';
COMMENT ON COLUMN MEMBER_ROLE.ROLE_NO IS '권한 식별번호';

CREATE TABLE URL_RESOURCE(
  RESOURCES_NO NUMBER PRIMARY KEY,
  URL_PATTERN VARCHAR2(50) NOT NULL,
  HTTP_METHOD VARCHAR2(10) NOT NULL
);
COMMENT ON TABLE URL_RESOURCE IS 'URL 자원';
COMMENT ON COLUMN URL_RESOURCE.RESOURCES_NO IS 'URL 식별번호';
COMMENT ON COLUMN URL_RESOURCE.URL_PATTERN IS 'URL 패턴';
COMMENT ON COLUMN URL_RESOURCE.HTTP_METHOD IS 'HTTP 메서드';

CREATE TABLE ROLE_RESOURCE(
  ROLE_NO NUMBER REFERENCES ROLE_INFO(ROLE_NO),
  RESOURCES_NO NUMBER REFERENCES URL_RESOURCE(RESOURCES_NO)
);
COMMENT ON TABLE ROLE_RESOURCE IS '권한-URL 자원';
COMMENT ON COLUMN ROLE_RESOURCE.ROLE_NO IS '권한 식별번호';
COMMENT ON COLUMN ROLE_RESOURCE.RESOURCES_NO IS '자원 식별번호';

CREATE TABLE COMPANY(
  COMPANY_NO NUMBER PRIMARY KEY,
  COMPANY_NAME VARCHAR2(330) NOT NULL,
  REPRESENTATIVE VARCHAR2(50),
  PHONE VARCHAR2(100),
  EMAIL VARCHAR2(300),
  CREATED_AT DATE,
  UPDATE_AT DATE
);
COMMENT ON TABLE COMPANY IS '회사';
COMMENT ON COLUMN COMPANY.COMPANY_NO IS '회사 식별번호';
COMMENT ON COLUMN COMPANY.REPRESENTATIVE IS '대표 이름';
COMMENT ON COLUMN COMPANY.PHONE IS '전화번호';
COMMENT ON COLUMN COMPANY.EMAIL IS '이메일';
COMMENT ON COLUMN COMPANY.CREATED_AT IS '창립일';
COMMENT ON COLUMN COMPANY.UPDATE_AT IS '갱신일';

CREATE TABLE COMPANY_ADDRESS(
  COMPANY_NO NUMBER REFERENCES COMPANY(COMPANY_NO),
  LATITUDE NUMBER NOT NULL,
  LONGITUDE NUMBER NOT NULL,
  SIDO VARCHAR2(70),
  SIGUNGU VARCHAR2(70),
  DONG VARCHAR2(70)
);
COMMENT ON TABLE COMPANY_ADDRESS IS '회사 주소';
COMMENT ON COLUMN COMPANY_ADDRESS.COMPANY_NO IS '회사 식별번호';
COMMENT ON COLUMN COMPANY_ADDRESS.LATITUDE IS '위도';
COMMENT ON COLUMN COMPANY_ADDRESS.LONGITUDE IS '경도';
COMMENT ON COLUMN COMPANY_ADDRESS.SIDO IS '시/도';
COMMENT ON COLUMN COMPANY_ADDRESS.SIGUNGU IS '시/군/구';
COMMENT ON COLUMN COMPANY_ADDRESS.DONG IS '읍/면/동';

CREATE TABLE SPECIALTY(
  SPECIALTY_NO NUMBER PRIMARY KEY,
  FIELD VARCHAR2(70) NOT NULL
);
COMMENT ON TABLE SPECIALTY IS '주 종목';
COMMENT ON COLUMN SPECIALTY.SPECIALTY_NO IS '종목 식별번호';
COMMENT ON COLUMN SPECIALTY.FIELD IS '종목';

CREATE TABLE COMPANY_SPECIALTY(
  COMPANY_NO NUMBER REFERENCES COMPANY(COMPANY_NO),
  SPECIALTY_NO NUMBER REFERENCES SPECIALTY(SPECIALTY_NO),
  MEMO VARCHAR2(70)
);
COMMENT ON TABLE COMPANY_SPECIALTY IS '회사-주 종목';
COMMENT ON COLUMN COMPANY_SPECIALTY.COMPANY_NO IS '회사 식별번호';
COMMENT ON COLUMN COMPANY_SPECIALTY.SPECIALTY_NO IS '종목 식별번호';
COMMENT ON COLUMN COMPANY_SPECIALTY.MEMO IS '기타종목 메모';