INSERT ALL
  INTO ROLE_INFO (ROLE_NO, NAME) VALUES (1, 'ROLE_ADMIN')
  INTO ROLE_INFO (ROLE_NO, NAME) VALUES (2, 'ROLE_EVALUATOR')
  INTO ROLE_INFO (ROLE_NO, NAME) VALUES (3, 'ROLE_VIEWER')

SELECT * FROM DUAL;