spring.application.name=treelink

#서버 포트번호
server.port=8080

#Thymeleaf 머릿말 꼬릿말
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

#파일 업로드용 MultipartResolver
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#ContextRoot 설정 
server.servlet.context-path=/

#오라클 설정
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/freepdb1

spring.datasource.username=TREELINK
spring.datasource.password=TREELINK

#마이바티스 설정 
mybatis.mapper-locations=classpath:mappers/*.xml

#오라클 null설정
#mybatis.configuration.jdbc-type-for-null=NULL
#언더바를 카멜표기법으로
#mybatis.configuration.map-underscore-to-camel-case=true

#하위패키지명을 별칭으로
#않이 내부 클래스 쓰면 자동 인식이 작동을 안 해요 세상에나
#mybatis.type-aliases-package=website.treelink

#xml설정 파일을 대신 둬 버그를 회피할 거에요
mybatis.config-location=classpath:mybatis-config.xml

#로그 레벨 설정
#전체 로그 레벨 설정 
logging.level.root=info

#패키지별 또는 클래스별 로그 레벨 설정
#logging.level.패키지경로 또는 클래스경로
#logging.level.website.treelink.board=debug
#logging.level.website.treelink.aop=debug

# 추가 설정 파일 인식
spring.config.import=classpath:key.properties