CREATE TABLE MEMBER(
  MEMBER_NO NUMBER PRIMARY KEY,
  ID VARCHAR2(300) NOT NULL,
  PWD VARCHAR2(300) NOT NULL,
  NAME VARCHAR2(300) NOT NULL,
  NICKNAME VARCHAR2(300) NOT NULL
);
COMMENT ON TABLE MEMBER IS '회원';
COMMENT ON COLUMN MEMBER.MEMBER_NO IS '아이디';
COMMENT ON COLUMN MEMBER.PWD IS '비밀번호';
COMMENT ON COLUMN MEMBER.NAME IS '이름';

CREATE TABLE ROLE_INFO(
  ROLE_NO NUMBER PRIMARY KEY,
  NAME VARCHAR2(30) NOT NULL
);
COMMENT ON TABLE ROLE_INFO IS '권한';
COMMENT ON COLUMN ROLE_INFO.ROLE_NO IS '권한 식별번호';
COMMENT ON COLUMN ROLE_INFO.NAME IS '권한 이름';

CREATE TABLE MEMBER_ROLE(
  MEMBER_NO NUMBER REFERENCES MEMBER(MEMBER_NO),
  ROLE_NO NUMBER REFERENCES ROLE_INFO(ROLE_NO)
);
COMMENT ON TABLE MEMBER_ROLE IS '회원-권한';
COMMENT ON COLUMN MEMBER_ROLE.MEMBER_NO IS '회원번호';
COMMENT ON COLUMN MEMBER_ROLE.ROLE_NO IS '권한 식별번호';

CREATE TABLE URL_RESOURCE(
  RESOURCES_NO NUMBER PRIMARY KEY,
  URL_PATTERN VARCHAR2(50) NOT NULL,
  HTTP_METHOD VARCHAR2(10) NOT NULL
);
COMMENT ON TABLE URL_RESOURCE IS 'URL 자원';
COMMENT ON COLUMN URL_RESOURCE.RESOURCES_NO IS 'URL 식별번호';
COMMENT ON COLUMN URL_RESOURCE.URL_PATTERN IS 'URL 패턴';
COMMENT ON COLUMN URL_RESOURCE.HTTP_METHOD IS 'HTTP 메서드';

CREATE TABLE ROLE_RESOURCE(
  ROLE_NO NUMBER REFERENCES ROLE_INFO(ROLE_NO),
  RESOURCES_NO NUMBER REFERENCES URL_RESOURCE(RESOURCES_NO)
);
COMMENT ON TABLE ROLE_RESOURCE IS '권한-URL 자원';
COMMENT ON COLUMN ROLE_RESOURCE.ROLE_NO IS '권한 식별번호';
COMMENT ON COLUMN ROLE_RESOURCE.RESOURCES_NO IS '자원 식별번호';

CREATE TABLE COMPANY(
  COMPANY_NO NUMBER PRIMARY KEY,
  BUSINESS_NO VARCHAR2(15) NOT NULL,
  COMPANY_NAME VARCHAR2(330) NOT NULL,
  REPRESENTATIVE_NAME VARCHAR2(33) NOT NULL,
  PHONE VARCHAR2(15) NOT NULL,
  EMAIL VARCHAR2(100),
  CREATED_ON DATE NOT NULL,
  STATUS VARCHAR2(15) NOT NULL DEFAULT 'ACTIVE'
);
COMMENT ON TABLE COMPANY IS '회사';
COMMENT ON COLUMN COMPANY.COMPANY_NO IS '회사 식별번호';
COMMENT ON COLUMN COMPANY.BUSINESS_NO IS '사업자 등록번호';
COMMENT ON COLUMN COMPANY.COMPANY_NAME IS '회사 이름';
COMMENT ON COLUMN COMPANY.REPRESENTATIVE_NAME IS '대표 이름';
COMMENT ON COLUMN COMPANY.PHONE IS '전화번호';
COMMENT ON COLUMN COMPANY.EMAIL IS '이메일';
COMMENT ON COLUMN COMPANY.CREATED_ON IS '창립일';
COMMENT ON COLUMN COMPANY.STATUS IS '상태';

CREATE TABLE ADDRESS(
  ADDRESS_NO NUMBER PRIMARY KEY,
  LATITUDE NUMBER,
  LONGITUDE NUMBER,
  ROAD_NAME VARCHAR2(330),
  SIDO VARCHAR2(70),
  SIGUNGU VARCHAR2(70)
);
COMMENT ON TABLE ADDRESS IS '회사 주소';
COMMENT ON COLUMN ADDRESS.ADDRESS_NO IS '회사 식별번호';
COMMENT ON COLUMN ADDRESS.LATITUDE IS '위도';
COMMENT ON COLUMN ADDRESS.LONGITUDE IS '경도';
COMMENT ON COLUMN ADDRESS.ROAD_NAME IS '도로명주소';
COMMENT ON COLUMN ADDRESS.SIDO IS '시/도';
COMMENT ON COLUMN ADDRESS.SIGUNGU IS '시/군/구';

CREATE TABLE COMPANY_ADDRESS(
  COMPANY_NO NUMBER REFERENCES COMPANY(COMPANY_NO),
  ADDRESS_NO NUMBER REFERENCES ADDRESS(ADDRESS_NO)
);
COMMENT ON TABLE COMPANY_ADDRESS IS '회사-주소';
COMMENT ON COLUMN COMPANY_ADDRESS.COMPANY_NO IS '회사 식별번호';
COMMENT ON COLUMN COMPANY_ADDRESS.ADDRESS_NO IS '주소 식별번호';

CREATE TABLE SPECIALTY(
  SPECIALTY_NO NUMBER PRIMARY KEY,
  FIELD VARCHAR2(70) NOT NULL
);
COMMENT ON TABLE SPECIALTY IS '주 종목';
COMMENT ON COLUMN SPECIALTY.SPECIALTY_NO IS '종목 식별번호';
COMMENT ON COLUMN SPECIALTY.FIELD IS '종목';

CREATE TABLE COMPANY_SPECIALTY(
  COMPANY_NO NUMBER REFERENCES COMPANY(COMPANY_NO),
  SPECIALTY_NO NUMBER REFERENCES SPECIALTY(SPECIALTY_NO),
  MEMO VARCHAR2(70)
);
COMMENT ON TABLE COMPANY_SPECIALTY IS '회사-주 종목';
COMMENT ON COLUMN COMPANY_SPECIALTY.COMPANY_NO IS '회사 식별번호';
COMMENT ON COLUMN COMPANY_SPECIALTY.SPECIALTY_NO IS '종목 식별번호';
COMMENT ON COLUMN COMPANY_SPECIALTY.MEMO IS '기타종목 메모';

CREATE TABLE EVALUATION(
  EVALUATION_NO NUMBER PRIMARY KEY,
  EVALUATION_TARGET NUMBER REFERENCES COMPANY(COMPANY_NO) NOT NULL,
  EVALUATE_BY NUMBER REFERENCES MEMBER(MEMBER_NO) NOT NULL,
  START_DATE DATE NOT NULL,
  END_DATE DATE NOT NULL,
  STATUS VARCHAR2(15)
);
COMMENT ON TABLE EVALUATION IS '평가';
COMMENT ON COLUMN EVALUATION.EVALUATION_TARGET IS '평가 대상';
COMMENT ON COLUMN EVALUATION.COMPANY_NO IS '회사 식별번호';
COMMENT ON COLUMN EVALUATION.EVALUATE_BY IS '평가자';
COMMENT ON COLUMN EVALUATION.START_DATE IS '시작 시각';
COMMENT ON COLUMN EVALUATION.END_DATE IS '종료 시각';
COMMENT ON COLUMN EVALUATION.STATUS IS '상태';

CREATE TABLE EVALUATION_ITEM(
  ITEM_NO NUMBER PRIMARY KEY,
  FIELD VARCHAR2(70)
);
COMMENT ON TABLE EVALUATION_ITEM IS '평가 항목';
COMMENT ON COLUMN EVALUATION_ITEM.COMPANY_NO IS '항목 식별번호';
COMMENT ON COLUMN EVALUATION_ITEM.SPECIALTY_NO IS '항목';

CREATE TABLE EVALUATION_SCORE(
  EVALUATION_NO NUMBER REFERENCES EVALUATION(EVALUATION_NO),
  ITEM_NO NUMBER REFERENCES EVALUATION_ITEM(ITEM_NO),
  SCORE NUMBER NOT NULL,
  RESON CLOB NOT NULL
);
COMMENT ON TABLE EVALUATION_SCORE IS '평가 항목';
COMMENT ON COLUMN EVALUATION_SCORE.EVALUATION_NO IS '항목 식별번호';
COMMENT ON COLUMN EVALUATION_SCORE.ITEM_NO IS '항목';
COMMENT ON COLUMN EVALUATION_SCORE.SCORE IS '점수';
COMMENT ON COLUMN EVALUATION_SCORE.RESON IS '이유';

CREATE TABLE EVALUATION_SCORE_HISTORY(
  EVALUATION_NO NUMBER REFERENCES EVALUATION(EVALUATION_NO),
  ITEM_NO NUMBER REFERENCES EVALUATION_ITEM(ITEM_NO),
  SCORE NUMBER NOT NULL,
  RESON CLOB NOT NULL,
  ACTION_AT DATE DEFAULT SYSDATE,
  ACTION_BY REFERENCES MEMBER(MEMBER_NO) NOT NULL,
  ACTION_RESON CLOB NOT NULL
);
COMMENT ON TABLE EVALUATION_SCORE_HISTORY IS '평가 항목';
COMMENT ON COLUMN EVALUATION_SCORE_HISTORY.EVALUATION_NO IS '항목 식별번호';
COMMENT ON COLUMN EVALUATION_SCORE_HISTORY.ITEM_NO IS '항목';
COMMENT ON COLUMN EVALUATION_SCORE_HISTORY.SCORE IS '점수';
COMMENT ON COLUMN EVALUATION_SCORE_HISTORY.RESON IS '이유';
COMMENT ON COLUMN EVALUATION_SCORE_HISTORY.ACTION_AT IS '변경 시각';
COMMENT ON COLUMN EVALUATION_SCORE_HISTORY.ACTION_BY IS '변경한 사람';
COMMENT ON COLUMN EVALUATION_SCORE_HISTORY.ACTION_RESON IS '변경 이유';