@startuml pageflow
actor "사용자" as User
participant "웹 브라우저" as Web
participant "스프링" as API
database "DB" as DB

User -> Web : 메인 화면 접속

alt 다른 페이지 이동 버튼 클릭
    User -> Front : 클릭
    Front -> API : GET /company/
    API --> Front : /company/main.html 응답
    Front --> User : 메인 화면 렌더링

else 로그인 된 경우 (상세 페이지 클릭)
    User -> Front : 상세 페이지 클릭
    Front -> API : GET /member/detail
    API --> Front : /member/detail.html 응답
    Front --> User : 상세 페이지 렌더링

else 로그인 안 된 경우
    User -> Front : 특정 기능 클릭
    Front -> API : 권한 체크 및 리다이렉트
    
    ' alt 내부에서 또 다른 alt(if-else)를 중첩해서 쓸 수 있습니다.
    alt 회원가입 선택
        User -> Front : 회원가입 버튼 클릭
        Front -> API : GET /member/join
        API --> Front : /member/join.html 응답
        Front --> User : 회원가입 페이지 렌더링
    else 로그인 선택
        User -> Front : 로그인 버튼 클릭
        Front -> API : GET /member/login
        API --> Front : /member/login.html 응답
        Front --> User : 로그인 페이지 렌더링
    end

end


@enduml